---
title: "Mortgage Lead Model"
author: "Radics, Gabor"
date: '2018-02-19'
output:
  html_notebook:
    df_print: paged
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
subtitle: Model Summary - 1 week
---

# 1 week

Summary of models' performance
```{r echo=FALSE}
B_resamps <- resamples(list("m00_logit_base" = m00_logit_base
                            #, "m01_logit_all" = m01_logit_all
                            , "m02_logit_penalized" = m02_logit_penalized
                            , "m03_rpart" = m03_rpart
                            , "m04_RF" = m04_RF
                            , "m05_pcr" = m05_pcr
                            , "m06_GBM" = m06_GBM
                            
                            , "m10_logit_base_factor" = m10_logit_base_factor
                            #, "m11_logit_all_factor" = m11_logit_all_factor
                            , "m12_logit_penalized_facor" = m12_logit_penalized_facor
                            , "m13_rpart_factor" = m13_rpart_factor
                            , "m14_RF_factor" = m14_RF_factor
                            , "m15_pcr_factor" = m15_pcr_factor
                            , "m16_GBM_factor" = m16_GBM_factor
                            
                            , "m20_logit_base_log" = m20_logit_base_log
                            #, "m21_logit_all_log" = m21_logit_all_log
                            , "m22_logit_penalized_log" = m22_logit_penalized_log
                            , "m23_rpart_log" = m23_rpart_log
                            , "m24_RF_log" = m24_RF_log
                            , "m25_pcr_log" = m25_pcr_log
                            , "m26_GBM_log" = m26_GBM_log
))

ROC_summary <- data.table(rbind(
  c('CV', summary(B_resamps)$statistics$ROC[,4])
  , c('Test'
      , m00_AUC_test
      #, m01_AUC_test
      , m02_AUC_test
      , m03_AUC_test
      , m04_AUC_test
      , m05_AUC_test
      , m06_AUC_test
      
      , m10_AUC_test
      #, m11_AUC_test
      , m12_AUC_test
      , m13_AUC_test
      , m14_AUC_test
      , m15_AUC_test
      , m16_AUC_test
      
      , m20_AUC_test
      #, m21_AUC_test
      , m22_AUC_test
      , m23_AUC_test
      , m24_AUC_test
      , m25_AUC_test
      , m26_AUC_test
      )
  , c('External'
      , m00_AUC_external
      #, m01_AUC_external
      , m02_AUC_external
      , m03_AUC_external
      , m04_AUC_external
      , m05_AUC_external
      , m06_AUC_external
      
      , m10_AUC_external
      #, m11_AUC_external
      , m12_AUC_external
      , m13_AUC_external
      , m14_AUC_external
      , m15_AUC_external
      , m16_AUC_external
      
      , m20_AUC_external
      #, m21_AUC_external
      , m22_AUC_external
      , m23_AUC_external
      , m24_AUC_external
      , m25_AUC_external
      , m26_AUC_external
      )
  ))

colnames(ROC_summary) <- c("dataset"
                           , "m00_logit_base"
                           #, "m01_logit_all"
                           , "m02_logit_penalized"
                           , "m03_rpart"
                           , "m04_RF"
                           , "m05_pcr"
                           , "m06_GBM"
                           
                           , "m10_logit_base_factor"
                           #, "m11_logit_all_factor"
                           , "m12_logit_penalized_facor"
                           , "m13_rpart_factor"
                           , "m14_RF_factor"
                           , "m15_pcr_factor"
                           , "m16_GBM_factor"
                           
                           , "m20_logit_base_log"
                           #, "m21_logit_all_log"
                           , "m22_logit_penalized_log"
                           , "m23_rpart_log"
                           , "m24_RF_log"
                           , "m25_pcr_log"
                           , "m26_GBM_log"
                           )

ROC_summary[,`:=`(
  m00_logit_base = as.numeric(specify_decimal(as.numeric(m00_logit_base), 4)),
  #m01_logit_all = as.numeric(specify_decimal(as.numeric(m01_logit_all), 4)),
  m02_logit_penalized = as.numeric(specify_decimal(as.numeric(m02_logit_penalized), 4)),
  m03_rpart = as.numeric(specify_decimal(as.numeric(m03_rpart), 4)),
  m04_RF = as.numeric(specify_decimal(as.numeric(m04_RF), 4)),
  m05_pcr = as.numeric(specify_decimal(as.numeric(m05_pcr), 4)),
  m06_GBM = as.numeric(specify_decimal(as.numeric(m06_GBM), 4)),
  
  m10_logit_base_factor = as.numeric(specify_decimal(as.numeric(m10_logit_base_factor), 4)),
  #m11_logit_all_factor = as.numeric(specify_decimal(as.numeric(m11_logit_all_factor), 4)),
  m12_logit_penalized_facor = as.numeric(specify_decimal(as.numeric(m12_logit_penalized_facor), 4)),
  m13_rpart_factor = as.numeric(specify_decimal(as.numeric(m13_rpart_factor), 4)),
  m14_RF_factor = as.numeric(specify_decimal(as.numeric(m14_RF_factor), 4)),
  m15_pcr_factor = as.numeric(specify_decimal(as.numeric(m15_pcr_factor), 4)),
  m16_GBM_factor = as.numeric(specify_decimal(as.numeric(m16_GBM_factor), 4)),
  
  m20_logit_base_log = as.numeric(specify_decimal(as.numeric(m20_logit_base_log), 4)),
  #m21_logit_all_log = as.numeric(specify_decimal(as.numeric(m21_logit_all_log), 4)),
  m22_logit_penalized_log = as.numeric(specify_decimal(as.numeric(m22_logit_penalized_log), 4)),
  m23_rpart_log = as.numeric(specify_decimal(as.numeric(m23_rpart_log), 4)),
  m24_RF_log = as.numeric(specify_decimal(as.numeric(m24_RF_log), 4)),
  m25_pcr_log = as.numeric(specify_decimal(as.numeric(m25_pcr_log), 4)),
  m26_GBM_log = as.numeric(specify_decimal(as.numeric(m26_GBM_log), 4))
)]

ROC_summary <- dcast(melt(ROC_summary, id.vars = "dataset"), variable ~ dataset)

ROC_summary
```

deleting what is not needed
```{r}
# continuous
rm(m00_logit_base)
#rm(m01_logit_all)
rm(m02_logit_penalized)
rm(m03_rpart)
rm(m04_RF)
rm(m05_pcr)
rm(m06_GBM)

# factor
rm(m10_logit_base_factor)
#rm(m11_logit_all_factor)
rm(m12_logit_penalized_facor)
rm(m13_rpart_factor)
rm(m14_RF_factor)
rm(m15_pcr_factor)
rm(m16_GBM_factor)

# log
rm(m20_logit_base_log)
#rm(m21_logit_all_log)
rm(m22_logit_penalized_log)
rm(m23_rpart_log)
rm(m24_RF_log)
rm(m25_pcr_log)
rm(m26_GBM_log)
```

